-- CNC MSP FORGE | HSF-GUIDE-01 guidance checks | local test harness only.
-- Proves migration 055 (build contract section 12.3, generated by
-- hsf/build_guidance.py) against a replayed database: every section, element,
-- appointment type and element class has guidance; the counts match the
-- worklist (15, 256, 41, 34) and the library; no text carries a provision
-- number other than section 16(2) and section 37(2); the shape rules of 12.1
-- hold; anon and authenticated read, only the service role writes; and
-- hsf_public_guidance returns the whole document. Never applied to Supabase.
-- Everything runs in one transaction that is rolled back.
--
-- Usage (from msp-forge/):
--   test/sql/replay.sh
--   psql -h /tmp -p 55432 -U postgres -d cnc_test -v ON_ERROR_STOP=1 -f test/sql/hsf_guidance_checks.sql
--
-- Every check prints "ok" as a notice; the first failure raises an exception that
-- stops the script with a non zero exit.

\set ON_ERROR_STOP 1
\pset pager off
begin;

-- 0. Harness ------------------------------------------------------------------------------

create function pg_temp.ok(p_name text, p_cond boolean) returns void language plpgsql as $$
begin
  if p_cond is distinct from true then
    raise exception 'CHECK FAILED: %', p_name;
  end if;
  raise notice 'ok   %', p_name;
end $$;

-- Runs p_sql and passes only when it is refused with a message matching p_pattern.
create function pg_temp.refuses(p_name text, p_sql text, p_pattern text) returns void language plpgsql as $$
declare
  v_msg text;
begin
  begin
    execute p_sql;
  exception when others then
    v_msg := sqlerrm;
  end;
  if v_msg is null then
    raise exception 'CHECK FAILED: % (the call succeeded, a refusal was expected)', p_name;
  end if;
  if v_msg !~* p_pattern then
    raise exception 'CHECK FAILED: % (refused with "%", expected /%/)', p_name, v_msg, p_pattern;
  end if;
  raise notice 'ok   % (refused: %)', p_name, v_msg;
end $$;

-- The number rule of contract sections 7 and 12.2, the same pattern as
-- hsf/build_guidance.py: true when the text names a provision number other than
-- section 16(2) or section 37(2).
create function pg_temp.numbered(p text) returns boolean language sql immutable as $$
  select regexp_replace(p, '\m(16|37)\(2\)', '', 'g') ~*
           ('\m(sections? [0-9]|ss?\. ?[0-9]|subsections? \(?[0-9]|regulations? [0-9]|regs?\.? ?[0-9]'
            || '|annexures? ([0-9]|[a-z]\M)|schedules? [0-9]|gnr? ?[0-9]|gn r\M|gg ?[0-9]|gazette (no\.? ?)?[0-9]'
            || '|no\. ?[0-9]+ of [0-9]{4}|[0-9]+ of (19|20)[0-9]{2}\M)'
            || '|\m[0-9]+\([0-9]+\)|\([0-9]+\)\([a-z]\)')
      or regexp_replace(p, '\m(16|37)\(2\)', '', 'g') ~ '\mR\.? ?[0-9]{3}'
$$;

-- Every string in the guidance document, with where it sits.
create temp view g_text as
select t.path, t.val
  from hsf_public_guidance v,
       lateral (
         select 'meta.note' as path, v.guidance #>> '{meta,note}' as val
         union all select 'first_file.intro', v.guidance #>> '{first_file,intro}'
         union all select 'first_file.order.' || (o ->> 'section'), o ->> 'reason'
           from jsonb_array_elements(v.guidance #> '{first_file,order}') o
         union all select 'first_file.before_you_start', b
           from jsonb_array_elements_text(v.guidance #> '{first_file,before_you_start}') b
         union all select k || '.' || e.key || '.' || f.key, x
           from unnest(array['sections','elements','appointments','classes']) k,
                jsonb_each(v.guidance -> k) e,
                jsonb_each(e.value) f,
                lateral (select f.value #>> '{}' as x where jsonb_typeof(f.value) = 'string'
                         union all select a from jsonb_array_elements_text(case when jsonb_typeof(f.value) = 'array' then f.value else '[]'::jsonb end) a) s
          where f.key <> 'who_usually_holds' and f.key <> 'suggested_department'
       ) t;

-- 1. Counts: the worklist and the library ------------------------------------------------

select pg_temp.ok('section guidance: 15 rows, one per library section',
  (select count(*) from hsf_section_guidance) = 15 and (select count(*) from hsf_section) = 15);
select pg_temp.ok('element guidance: 256 rows, one per library element',
  (select count(*) from hsf_element_guidance) = 256 and (select count(*) from hsf_element) = 256);
select pg_temp.ok('appointment guidance: 41 rows, one per appointment type',
  (select count(*) from hsf_appointment_guidance) = 41 and (select count(*) from hsf_appointment_type) = 41);
select pg_temp.ok('class guidance: 34 rows, one per element class',
  (select count(*) from hsf_class_guidance) = 34 and (select count(*) from hsf_element_class) = 34);
select pg_temp.ok('guidance meta: exactly one row', (select count(*) from hsf_guidance_meta) = 1);

-- 2. Every library item has guidance ----------------------------------------------------

select pg_temp.ok('every section has guidance',
  not exists (select 1 from hsf_section s where not exists (select 1 from hsf_section_guidance g where g.section_code = s.code)));
select pg_temp.ok('every element has guidance, universal and overlay',
  not exists (select 1 from hsf_element e where not exists (select 1 from hsf_element_guidance g where g.element_code = e.code)));
select pg_temp.ok('every appointment type has guidance',
  not exists (select 1 from hsf_appointment_type a where not exists (select 1 from hsf_appointment_guidance g where g.appointment_code = a.code)));
select pg_temp.ok('every course, licence and examination class has guidance',
  not exists (select 1 from hsf_element_class c where not exists (select 1 from hsf_class_guidance g where g.class_code = c.code)));
select pg_temp.refuses('guidance for an unknown element is refused',
  $q$insert into hsf_element_guidance (element_code, what_to_submit, why, example, suggested_department)
     values ('HSF-Z-99', '["a","b"]', 'why', 'Example: x', 'SHE')$q$, 'foreign key');
select pg_temp.refuses('guidance naming an unknown department is refused',
  $q$update hsf_element_guidance set suggested_department = 'XX' where element_code = 'HSF-A-01'$q$, 'foreign key');

-- 3. No provision numbers other than section 16(2) and section 37(2) ----------------------

select pg_temp.ok('number rule: catches planted provision numbers',
  pg_temp.numbered('see regulation 3 of the rules') and pg_temp.numbered('under section 8(1)') and pg_temp.numbered('GNR 1010')
  and pg_temp.numbered('Annexure 3 certificate') and pg_temp.numbered('Act 85 of 1993') and pg_temp.numbered('R638 hygiene')
  and pg_temp.numbered('a 24(1) report') and pg_temp.numbered('Gazette No. 4123'));
select pg_temp.ok('number rule: allows section 16(2), section 37(2), dates and rand',
  not pg_temp.numbered('the section 16(2) assignee and the section 37(2) agreement')
  and not pg_temp.numbered('Example: dated 14 May 2026, 25 staff, R4 250,00')
  and not pg_temp.numbered('the Construction Regulations, 2014'));
select pg_temp.ok('the guidance document carries text to check (more than 2 000 strings)',
  (select count(*) from g_text) > 2000);
do $$
declare
  v text;
begin
  select string_agg(path || ': ' || val, ' | ') into v from (select * from g_text where pg_temp.numbered(val) limit 5) x;
  if v is not null then raise exception 'CHECK FAILED: provision numbers in guidance: %', v; end if;
  raise notice 'ok   no guidance text carries a provision number other than section 16(2) or section 37(2)';
end $$;
select pg_temp.ok('no guidance text uses "compliant", "guarantee" or dash punctuation',
  not exists (select 1 from g_text where val ~* '\mcompliant\M|guarantee' or val ~ '[‒–—―]| - '));
select pg_temp.ok('no guidance text names the NIHL Regulations or the Environmental Regulations for Workplaces',
  not exists (select 1 from g_text where val ~* 'NIHL Regulations|Environmental Regulations for Workplaces'));

-- 4. Shape (contract 12.1) ---------------------------------------------------------------

select pg_temp.ok('elements: 2 to 5 items to submit, 0 to 3 gaps, an example marked as one',
  not exists (select 1 from hsf_element_guidance
               where jsonb_array_length(what_to_submit) not between 2 and 5 or jsonb_array_length(common_gaps) > 3
                  or example not like 'Example%' or length(btrim(why)) = 0));
select pg_temp.ok('appointments and classes: the same shape, and no suggested department',
  not exists (select 1 from hsf_appointment_guidance
               where jsonb_array_length(what_to_submit) not between 2 and 5 or jsonb_array_length(common_gaps) > 3 or example not like 'Example%')
  and not exists (select 1 from hsf_class_guidance
               where jsonb_array_length(what_to_submit) not between 2 and 5 or jsonb_array_length(common_gaps) > 3 or example not like 'Example%')
  and not exists (select 1 from information_schema.columns
                   where table_name in ('hsf_appointment_guidance', 'hsf_class_guidance') and column_name = 'suggested_department'));
select pg_temp.refuses('an element with one item to submit is refused',
  $q$update hsf_element_guidance set what_to_submit = '["only one"]' where element_code = 'HSF-A-01'$q$, 'check constraint');
select pg_temp.refuses('an example not marked as an example is refused',
  $q$update hsf_class_guidance set example = 'Dube Engineering files it.' where class_code = 'D04-01'$q$, 'check constraint');
select pg_temp.ok('sections: who usually holds names known departments only, and the first is a department',
  not exists (select 1 from hsf_section_guidance g, unnest(g.who_usually_holds) d where d not in (select code from hsf_department)));
select pg_temp.ok('first File: the recommended order names all fifteen sections once',
  (select count(distinct o ->> 'section') = 15 and count(*) = 15
     and bool_and((o ->> 'section') in (select code from hsf_section)) and bool_and(length(o ->> 'reason') > 0)
     from hsf_guidance_meta m, jsonb_array_elements(m.first_file_order) o));
select pg_temp.ok('meta: HSF-GUIDE-1.0, draft, not yet reviewed, with a note',
  (select version = 'HSF-GUIDE-1.0' and status = 'draft' and reviewed_by is null and length(note) > 0 from hsf_guidance_meta));

-- 5. The public document ------------------------------------------------------------------

select pg_temp.ok('hsf_public_guidance: one document with every part and every count',
  (select count(*) = 1 from hsf_public_guidance)
  and (select (select count(*) from jsonb_object_keys(guidance -> 'sections')) = 15
          and (select count(*) from jsonb_object_keys(guidance -> 'elements')) = 256
          and (select count(*) from jsonb_object_keys(guidance -> 'appointments')) = 41
          and (select count(*) from jsonb_object_keys(guidance -> 'classes')) = 34
          and jsonb_array_length(guidance #> '{first_file,order}') = 15
          and guidance #>> '{meta,version}' = 'HSF-GUIDE-1.0'
          and guidance #>> '{elements,HSF-A-01,suggested_department}' is not null
          and jsonb_typeof(guidance #> '{sections,B,who_usually_holds}') = 'array'
         from hsf_public_guidance));

-- 6. Access: anyone reads, only the service role writes ------------------------------------

select pg_temp.ok('row level security is on for every guidance table',
  (select bool_and(relrowsecurity) and count(*) = 5 from pg_class
    where relname in ('hsf_guidance_meta','hsf_section_guidance','hsf_element_guidance','hsf_appointment_guidance','hsf_class_guidance')));
select pg_temp.ok('the view runs with the caller''s rights (security_invoker)',
  (select coalesce('security_invoker=true' = any(reloptions), false) from pg_class where relname = 'hsf_public_guidance'));

set local role anon;
select pg_temp.ok('anon reads every guidance table and the view',
  (select count(*) from hsf_element_guidance) = 256 and (select count(*) from hsf_section_guidance) = 15
  and (select count(*) from hsf_appointment_guidance) = 41 and (select count(*) from hsf_class_guidance) = 34
  and (select count(*) from hsf_guidance_meta) = 1
  and (select count(*) from jsonb_object_keys((select guidance from hsf_public_guidance) -> 'elements')) = 256);
select pg_temp.refuses('anon cannot write guidance',
  $q$update hsf_element_guidance set why = 'changed' where element_code = 'HSF-A-01'$q$, 'permission denied');
reset role;

set local role authenticated;
select pg_temp.ok('authenticated reads the guidance', (select count(*) from hsf_class_guidance) = 34);
select pg_temp.refuses('authenticated cannot insert guidance',
  $q$insert into hsf_section_guidance (section_code, intro, what_goes_here, who_usually_holds, first_file_tips)
     values ('A', 'x', '["x"]', array['SHE'], '[]')$q$, 'permission denied');
select pg_temp.refuses('authenticated cannot delete guidance',
  $q$delete from hsf_guidance_meta$q$, 'permission denied');
reset role;

set local role service_role;
with u as (update hsf_element_guidance set why = why where element_code = 'HSF-A-01' returning 1)
select pg_temp.ok('the service role writes guidance', (select count(*) = 1 from u));
reset role;

rollback;
\echo 'hsf_guidance_checks: all checks passed'
