// Fictional demo data mirroring the Supabase schema (app_user, unit, device, vehicle, clock_event, inspection, stock_item, stock_movement, incident, newsletter, agent_report). All persons are fictional.
window.CNC = {
today: 'Thursday 6 August 2026',
quotes:[
 {q:'I am because we are.',a:'Ubuntu proverb'},
 {q:'A person is a person through other persons.',a:'Ubuntu philosophy'},
 {q:'It always seems impossible until it is done.',a:'Nelson Mandela'},
 {q:'My humanity is bound up in yours, for we can only be human together.',a:'Desmond Tutu'},
 {q:'If you want to go fast, go alone. If you want to go far, go together.',a:'African proverb'},
 {q:'Try to be a rainbow in someone else\u2019s cloud.',a:'Maya Angelou'},
 {q:'Waste no more time arguing about what a good person should be. Be one.',a:'Marcus Aurelius'},
 {q:'Wherever there is a human being, there is an opportunity for kindness.',a:'Seneca'},
 {q:'What you do makes a difference, and you have to decide what kind of difference you want to make.',a:'Jane Goodall'},
 {q:'However difficult life may seem, there is always something you can do and succeed at.',a:'Stephen Hawking'},
 {q:'Courage is not the absence of fear, but the triumph over it.',a:'Nelson Mandela'},
 {q:'Alone we can do so little; together we can do so much.',a:'Helen Keller'},
 {q:'Each patient carries his own doctor inside him.',a:'Albert Schweitzer'},
 {q:'The purpose of human life is to serve, and to show compassion and the will to help others.',a:'Albert Schweitzer'},
],
units: [
 {id:'u1',unit_type:'clinic',name:'Midrand Clinic'},
 {id:'u2',unit_type:'clinic',name:'Elandsfontein Clinic'},
 {id:'u3',unit_type:'clinic',name:'Gqeberha Clinic'},
 {id:'u4',unit_type:'clinic',name:'Brackenfell Clinic'},
 {id:'u5',unit_type:'mobile_clinic',name:'Trailer 1 (TRN001)'},
 {id:'u6',unit_type:'mobile_clinic',name:'Trailer 2'},
],
jobcards: [
 {ref:'MS038605',client:'Murray & Dickson Construction (Pty) Ltd',branch:'Midrand - Site',asset:'Trailer 1 (TRN001)',vehicle:'Isuzu D-Max LT39HNGP · CNC-AST-VEH-002',office_time:'05:30 at office',site_time:'08:00 at site',booked:36,medicals:'General: 36 · exit medicals',quote:'QUO000173811',po:'No PO provided',site_contact:'Site contact: T. Site Supervisor · 011 000 0000',address:'Modimolle, 0510, Limpopo',distance:'158 km · 1 h 47 min',travel:true,geofence:'Guesthouse, Modimolle (travel job)',start:'08:00',notes:['Exit medicals.','Drug test first on site. A non negative stops the full medical.','Site and supervisor name required with every booking.','Actual PO required. No PO, no booking.'],team:[{name:'Thandi Mokoena',duties:'Driver, height and weight, capturing, physicals'},{name:'Sipho Dlamini',duties:'Audiometry, spirometry, vision'},{name:'Naledi Khumalo',duties:'Spirometry, additional questionnaires'}]},
 {ref:'MS038607',client:'Tswelopele Convenience Centre',branch:'Midrand - Site',asset:'Trailer 2',vehicle:'Isuzu D-Max KZ66CKGP · CNC-AST-VEH-004',office_time:'06:00 at office',site_time:'08:00 at site',booked:21,medicals:'General: 21',quote:'QUO000173839',po:'—',site_contact:'Site contact: N. Site Supervisor · 069 000 0000',address:'357 Indlovu Ave, Thembisa, 1666',distance:'10.3 km · 16 min',travel:false,geofence:'Client site, Thembisa',start:'08:00',notes:[],team:[{name:'Johan van Wyk',duties:'Driver, height and weight, capturing'},{name:'Lerato Nkosi',duties:'Physicals, additional questionnaires'}]},
],
tomorrowJobcard:{ref:'MS038609',date:'Friday 7 August',client:'G4S Secure Solutions (Embassy)',branch:'Midrand - Site',asset:'Trailer 1 (TRN001)',vehicle:'Isuzu D-Max LT39HNGP · CNC-AST-VEH-002',office_time:'06:00 at office',site_time:'08:00 at site',booked:50,medicals:'General: 50',address:'852 Park St, Arcadia, Pretoria, 0007',distance:'29.6 km · 30 min',uploaded:'16:24 today',note:'Ops Manager: 50 medicals booked, pack double spirometry mouthpieces and extra multi drug tests. Confirm the trailer fridge is on charge tonight.',packing:['Audiometer, spirometer and vision screener with daily check kit','Disposables: gloves, mouthpieces, ear tips, couch roll','Multi drug tests × 50 plus spares','Calibration certificates in the trailer file','Vehicle: fuel, tyre check, licence disc visible']},
myJobcards: [
 {ref:'MS038584',date:'05/08/2026',client:'WSP Group Africa',branch:'Midrand - Site',hours:'06:00 to 15:40',status:'Completed',rating:4.7,reviews:2},
 {ref:'MS038571',date:'04/08/2026',client:'Mitek Industries SA (Pty) Ltd',branch:'Midrand - Site',hours:'06:00 to 16:10',status:'Completed',rating:5.0,reviews:1},
 {ref:'CLN-MID-0308',date:'03/08/2026',client:'Midrand Clinic, Shift 1',branch:'Midrand - Clinic',hours:'07:00 to 16:00',status:'Completed',rating:4.2,reviews:1},
 {ref:'MS038522',date:'31/07/2026',client:'G4S Secure Solutions',branch:'Midrand - Site',hours:'06:00 to 15:20',status:'Completed',rating:2.8,reviews:1,flagged:true},
],
gmb:{'Cape Town':'https://g.co/kgs/gd7vAYT','Elandsfontein':'https://g.co/kgs/9cDtyWF','Gqeberha':'https://g.co/kgs/uSoimfZ','Midrand':'https://g.co/kgs/XP2EuBM'},
reviewLeaders:[{name:'Sipho Dlamini',count:14},{name:'Thandi Mokoena',count:11},{name:'Naledi Khumalo',count:8}],
wallet:{balance:185,events:[
 {at:'05/08/2026 14:12',client:'WSP Group Africa',amount:2,what:'5 star review · R6 split, team of 3'},
 {at:'05/08/2026 11:03',client:'WSP Group Africa',amount:2,what:'4 star review · R6 split, team of 3'},
 {at:'04/08/2026 13:40',client:'Mitek Industries SA',amount:2,what:'5 star review · R6 split, team of 3'},
 {at:'31/07/2026 10:22',client:'G4S Secure Solutions',amount:0,what:'2.8 stars · no payout, sent to Operations Manager'},
]},
roster: [
 {id:'p1',first:'Thandi',last:'Mokoena',emp:'CNC0142',role:'OHS practitioner',status:'in',time:'06:48'},
 {id:'p2',first:'Sipho',last:'Dlamini',emp:'CNC0155',role:'Audiometrist',status:'in',time:'06:52'},
 {id:'p3',first:'Lerato',last:'Nkosi',emp:'CNC0161',role:'Wellness nurse',status:'out',time:null},
 {id:'p4',first:'Johan',last:'van Wyk',emp:'CNC0128',role:'Driver and technician',status:'out',time:null},
 {id:'p5',first:'Naledi',last:'Khumalo',emp:'CNC0170',role:'Spirometry technician',status:'flagged',time:'06:41'},
 {id:'p6',first:'Pieter',last:'Botha',emp:'CNC0134',role:'Unit manager',status:'out',time:null},
],
devices: [
 {id:'d1',barcode:'CNC-AUD-0031',device_type:'Audiometer',make:'Interacoustics AD629',serial:'AD6-88412',unit:'Trailer 1 (TRN001)',status:'in_service',calibration_expiry:'14/11/2026',lifetime:12480,since_cal:642,avg_daily:38,service_in:41},
 {id:'d2',barcode:'CNC-SPI-0017',device_type:'Spirometer',make:'Vitalograph Pneumotrac',serial:'VP-20441',unit:'Trailer 1 (TRN001)',status:'in_service',calibration_expiry:'02/10/2026',lifetime:9120,since_cal:512,avg_daily:29,service_in:63},
 {id:'d3',barcode:'CNC-VIS-0009',device_type:'Vision screener',make:'Keystone VS V',serial:'KS-11208',unit:'Trailer 1 (TRN001)',status:'do_not_use',calibration_expiry:'21/08/2026',lifetime:15840,since_cal:890,avg_daily:44,service_in:12},
 {id:'d4',barcode:'CNC-HWS-0004',device_type:'Height and weight station',make:'Seca 285',serial:'SC-77031',unit:'Midrand Clinic',status:'in_service',calibration_expiry:'30/01/2027',lifetime:22110,since_cal:1204,avg_daily:51,service_in:88},
],
vehicles: [
 {id:'v1',registration:'LT 39 HN GP',make_model:'Isuzu D-Max · CNC-AST-VEH-002 (Trailer 1)',odo:184220,disc_expiry:'28/08/2026',disc_days:22,service_km:190000},
 {id:'v2',registration:'KZ 66 CK GP',make_model:'Isuzu D-Max · CNC-AST-VEH-004 (Trailer 2)',odo:96410,disc_expiry:'15/02/2027',disc_days:193,service_km:100000},
],
equipChecklist: [
 {code:'PWR',label:'Powers on and self test completes',critical:true},
 {code:'CAL',label:'Calibration sticker present and in date',critical:true},
 {code:'CBL',label:'Cables and transducers undamaged',critical:false},
 {code:'HYG',label:'Contact surfaces cleaned and disinfected',critical:false},
 {code:'CSE',label:'Carry case and accessories complete',critical:false},
],
facilityChecklist: [
 {code:'CLN',label:'Floors and surfaces clean',critical:false},
 {code:'SGN',label:'Required signage displayed',critical:false},
 {code:'CON',label:'Consumables stocked at station',critical:false},
 {code:'WST',label:'Waste segregated correctly',critical:true},
 {code:'SFT',label:'Fire extinguisher and first aid accessible',critical:true},
],
vehicleChecklist: [
 {code:'TYR',label:'Tyres, tread and pressure',critical:true},
 {code:'LGT',label:'Lights and indicators working',critical:true},
 {code:'FLD',label:'Oil, coolant and washer fluid levels',critical:false},
 {code:'WIP',label:'Wipers and windscreen condition',critical:false},
 {code:'FAK',label:'First aid kit sealed and present',critical:false},
 {code:'EXT',label:'Fire extinguisher charged and secured',critical:true},
],
vehicleShots: ['Front','Rear','Left side','Right side','Cabin','Load area','Odometer','Licence disc'],
departments: ['Reception','Audiometry','Spirometry','Vision','Medical station','Ablutions'],
calibChecks: {
 'Audiometer': {name:'Daily biological check', fields:[{k:'500 Hz reading (dB HL)',nominal:10,tol:5},{k:'1000 Hz reading (dB HL)',nominal:10,tol:5},{k:'4000 Hz reading (dB HL)',nominal:15,tol:5}]},
 'Spirometer': {name:'3 litre syringe verification', fields:[{k:'Syringe volume reading (L)',nominal:3.0,tol:0.09}]},
 'Vision screener': {name:'Daily slide verification', fields:[{k:'Reference slide score',nominal:20,tol:0}]},
},
stock: [
 {id:'s1',name:'Nitrile gloves (box 100)',uom:'box',min:10,on_hand:24},
 {id:'s2',name:'Spirometry mouthpieces',uom:'pack 50',min:6,on_hand:4},
 {id:'s3',name:'Audiometry ear tips',uom:'pack 100',min:4,on_hand:9},
 {id:'s4',name:'Couch roll',uom:'roll',min:8,on_hand:12},
 {id:'s5',name:'Alcohol swabs',uom:'box 200',min:5,on_hand:3},
 {id:'s6',name:'Disinfectant wipes',uom:'tub',min:6,on_hand:15},
],
movements: [
 {item:'Spirometry mouthpieces',type:'take',qty:2,by:'Naledi Khumalo',at:'06:58 today'},
 {item:'Nitrile gloves (box 100)',type:'take',qty:1,by:'Thandi Mokoena',at:'06:51 today'},
 {item:'Alcohol swabs',type:'add',qty:5,by:'Pieter Botha',at:'16:12 yesterday'},
 {item:'Couch roll',type:'correction',qty:2,by:'Pieter Botha',at:'15:40 yesterday'},
],
incidentTypes: ['Injury on duty','Near miss','Equipment damage','Vehicle incident','Property or security','Other'],
newsletters: [
 {title:'Care Net Connect, August 2026',date:'01/08/2026',pages:6},
 {title:'Care Net Connect, July 2026',date:'01/07/2026',pages:8},
 {title:'Care Net Connect, June 2026',date:'02/06/2026',pages:6},
 {title:'Winter Wellness Special',date:'19/05/2026',pages:4},
 {title:'Care Net Connect, May 2026',date:'01/05/2026',pages:6},
 {title:'Care Net Connect, April 2026',date:'01/04/2026',pages:8},
],
pendingUsers: [
 {name:'Zanele Mthembu',emp:'CNC0183',email:'z.mthembu@carenet.example',unit:'Gqeberha Clinic',submitted:'05/08/2026',consent:true},
 {name:'Daniel Petersen',emp:'CNC0184',email:'d.petersen@carenet.example',unit:'Mobile Unit 2',submitted:'04/08/2026',consent:true},
],
agentReport: {
 date:'06/08/2026', generated:'05:02 SAST',
 summary:{high:2,medium:3,low:4},
 items:[
  {sev:'high',title:'Vision screener CNC-VIS-0009 out of tolerance',body:'Daily slide verification on Trailer 1 (TRN001) read 17 against a nominal 20 with zero tolerance. Device set to do not use at 06:41. No vision tests were logged after the flag. Decision needed: send for calibration or swap with the Midrand spare.'},
  {sev:'high',title:'Clock event flagged for review',body:'Photo verification for N. Khumalo at 06:41 returned confidence 0.58, below the 0.80 threshold. Event written as flagged, not discarded. A super user must confirm or reject the event.'},
  {sev:'medium',title:'Licence disc expires in 22 days',body:'LT 39 HN GP, Isuzu D-Max on Trailer 1, disc expires 28/08/2026. Renewal has not been logged.'},
  {sev:'medium',title:'Two stock lines below minimum',body:'Spirometry mouthpieces at 4 against a minimum of 6, alcohol swabs at 3 against a minimum of 5, both on Trailer 1 (TRN001). Reorder flags raised.'},
  {sev:'medium',title:'Facility inspection missed',body:'Elandsfontein Clinic did not submit its daily facility inspection yesterday. All other units submitted on time.'},
  {sev:'low',title:'Service projection update',body:'Audiometer CNC-AUD-0031 projects service in 41 days at trailing volume of 38 tests per day. No out of tolerance events since last calibration.'},
 ]
}
};
