-- CNC-IT-SAL-003 v0.1.0 — approved by Quintis Nel, applied 20/07/2026
-- Q3 resolved as proposed: moddatetime triggers included.

create table public.sales_consultant (
  ghl_user_id  text primary key,
  display_name text not null,
  user_id      uuid unique references public.user_profiles(id),
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.sales_consultant is
  'Bridge between GHL user IDs (pipeline data) and portal accounts (auth). '
  'user_id NULL = consultant has no portal account yet and cannot read briefs. '
  'Writes via service role only. Owner: MA-CN-003 build (CNC-IT-SAL-003).';

insert into public.sales_consultant (ghl_user_id, display_name) values
  ('U8pZMnuDQnJzghmcw54b', 'Sire van Zyl'),
  ('IgJ1euJjU8LoKrTEx1Uz', 'Gladys Mgitywa'),
  ('SGrLQugQabeTWb4wBe7Q', 'Celeste Bulpitt'),
  ('52sed7BeubVEIoakOR61', 'Elsie Lubisi'),
  ('j8ufOBqYgnfuNuwoZYHA', 'Maryna Ferreira'),
  ('BUmbSNmCrifMiDP5wgt1', 'Annemarie Lotter');

create table public.sales_assistant_brief (
  id            uuid primary key default gen_random_uuid(),
  brief_date    date not null,
  scope         text not null check (scope in ('consultant','management')),
  ghl_user_id   text references public.sales_consultant(ghl_user_id),
  body_md       text not null,
  brief_data    jsonb not null default '{}'::jsonb,
  model         text not null,
  input_tokens  integer,
  output_tokens integer,
  generated_at  timestamptz not null default now(),
  constraint brief_scope_owner_coherent
    check ((scope = 'consultant') = (ghl_user_id is not null)),
  constraint brief_one_per_day
    unique nulls not distinct (brief_date, scope, ghl_user_id)
);

comment on table public.sales_assistant_brief is
  'MA-CN-003 daily briefs. Generated by the sales-assistant-brief edge function '
  '(service role); no human writes. scope=consultant -> private to that consultant; '
  'scope=management -> aggregate only during pilot, readable by sales + directors + admins. '
  'POPIA: no contact email/phone may ever appear here (agent rule 8). '
  'Retention: operational — purge policy pending confirmation (CNC-IT-SAL-003 s2.5).';

create index brief_by_consultant
  on public.sales_assistant_brief (ghl_user_id, brief_date desc);
create index brief_by_date
  on public.sales_assistant_brief (brief_date desc);

create table public.sales_assistant_task (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.user_profiles(id),
  title        text not null check (char_length(title) between 1 and 200),
  details      text,
  due_date     date,
  status       text not null default 'open'
               check (status in ('open','done','dropped')),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  completed_at timestamptz
);

comment on table public.sales_assistant_task is
  'Consultant-authored tasks. The agent RANKS these in the daily brief; it never '
  'creates, edits, or deletes them (MA-CN-003 rule 6). Private to the author. '
  'Free text may incidentally contain client names — covered by the operational '
  'retention class, and consultants are briefed not to record clinical details.';

create index task_by_owner_status
  on public.sales_assistant_task (user_id, status);
create index task_open_by_due
  on public.sales_assistant_task (due_date)
  where status = 'open';

alter table public.sales_consultant       enable row level security;
alter table public.sales_assistant_brief  enable row level security;
alter table public.sales_assistant_task   enable row level security;

create policy consultant_directory_read
  on public.sales_consultant
  for select to authenticated
  using (true);

create policy brief_read
  on public.sales_assistant_brief
  for select to authenticated
  using (
    ( scope = 'consultant'
      and exists (
        select 1 from public.sales_consultant sc
        where sc.ghl_user_id = sales_assistant_brief.ghl_user_id
          and sc.user_id     = (select auth.uid())
      )
    )
    or
    ( scope = 'management'
      and exists (
        select 1 from public.user_roles ur
        where ur.user_id = (select auth.uid())
          and ( ur.role in ('owner','administrator')
                or ur.department in ('sales','directors') )
      )
    )
  );

create policy task_select_own
  on public.sales_assistant_task
  for select to authenticated
  using (user_id = (select auth.uid()));

create policy task_insert_own
  on public.sales_assistant_task
  for insert to authenticated
  with check (user_id = (select auth.uid()));

create policy task_update_own
  on public.sales_assistant_task
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy task_delete_own
  on public.sales_assistant_task
  for delete to authenticated
  using (user_id = (select auth.uid()));

create extension if not exists moddatetime schema extensions;

create trigger set_updated_at before update on public.sales_consultant
  for each row execute procedure extensions.moddatetime(updated_at);
create trigger set_updated_at before update on public.sales_assistant_task
  for each row execute procedure extensions.moddatetime(updated_at);
